### ISSUE TITLE
Building

### ISSUE THREAD

**Issue by karolisg** [collinss/calculator-desklet#1]
How to build it?

**Comment by collinss** [comment]
You don't actually need to build anything. If you want the latest stable you can simply get it from the desklet settings in cinnamon. If you want the latest (development) version, and have git installed, you can simply type from a command prompt:

```
git clone https://github.com/collinss/calculator-desklet.git ~/.local/share/cinnamon/desklets/calculator@scollins
cd ~/.local/share/cinnamon/desklets/calculator@scollins/
git checkout rework
```

Alternatively, you can select the rework branch from the main page of this repository, download as zip and extract to `~/.local/share/cinnamon/desklets/`. (Be sure to change the name of the folder to `calculator@scolllins` or it will not work.)

After installing, you will need to add it to the desktop through desklet settings.

**Comment by karolisg** [comment]
I want to develop it, but every time I make changes - I need restart cinnamon. Is there any way to see changes without restart?

**Comment by collinss** [comment]
You can reload just the desklet code through Looking Glass, or you can do the same from my Developers Tools desklet on the Cinnamon Spices website.
